version: '3'
services:
  magic:
    image: mageai/mageai:latest
    container_name: mage
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: dev
      SPACETRACK_API_PW: ${SPACETRACK_API_PW}
      SPACETRACK_USER: ${SPACETRACK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: defaultdb      
      MB_DB_PORT: 25060           
      MB_DB_USER: doadmin         
      MB_DB_PASS: ${POSTGRES_PASSWORD}   
      MB_DB_HOST: dma-prod-pgsql-syd-00-do-user-16032706-0.c.db.ondigitalocean.com  
      MB_DB_SSLMODE: require                 
    restart: on-failure
  
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    #environment:
      #MB_DB_TYPE: postgres
      #MB_DB_DBNAME: defaultdb
      #MB_DB_PORT: 25060
      #MB_DB_USER: doadmin
      #MB_DB_PASS: ${POSTGRES_PASSWORD}   
      #MB_DB_HOST: dma-prod-pgsql-syd-00-do-user-16032706-0.c.db.ondigitalocean.com 
    command: >
      --url="jdbc:postgresql://dma-prod-pgsql-syd-00-do-user-16032706-0.c.db.ondigitalocean.com:25060/defaultdb?user=doadmin&password=${POSTGRES_PASSWORD}" 
      --changeLogFile=changelog.xml status
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts